In [1]:
import numpy as np


In [2]:
lst = [1,2,3,4,5,6]
print(lst)
print(type(lst))

[1, 2, 3, 4, 5, 6]
<class 'list'>


In [3]:
arr_lst = np.array(lst)
arr_lst

array([1, 2, 3, 4, 5, 6])

In [4]:
tup=(1,2,3,4,5)
print(tup)
print(type(tup))
arr_tup = np.array(tup)

(1, 2, 3, 4, 5)
<class 'tuple'>


In [5]:
tup=(1,2,3,4,5)
print(tup)
print(type(tup))
arr_tup = np.array(tup)
print(arr_tup)

(1, 2, 3, 4, 5)
<class 'tuple'>
[1 2 3 4 5]


In [6]:
tup=(1,2,3,4,5)
print(tup)
print(type(tup))
arr_tup = np.array(tup)
print(arr_tup)
print(type(arr_tup))

(1, 2, 3, 4, 5)
<class 'tuple'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
lst = [1,2,3,4,5,6]
print(lst)
print(type(lst))
arr_lst = np.array(lst)
arr_lst.shape
arr_lst.ndim
arr_0d=np.array(5)
arr_0d
arr_0d.ndim


[1, 2, 3, 4, 5, 6]
<class 'list'>


0

In [8]:
lst = [1,2,3,4,5,6]
print(lst)
print(type(lst))
arr_lst = np.array(lst)
print(arr_lst.shape)
print(arr_lst.ndim)
arr_0d=np.array(5)
print(arr_0d)
print(arr_0d.ndim)

[1, 2, 3, 4, 5, 6]
<class 'list'>
(6,)
1
5
0


In [9]:
lst_2d = [[1,2,3,4,5],[6,7,8,9,10]]
lst_2d
arr_2d= np.array(lst_2d)
arr_2d
print(type(arr_2d))



<class 'numpy.ndarray'>


In [10]:
lst_2d = [[1,2,3,4,5],[6,7,8,9,10]]
lst_2d
arr_2d= np.array(lst_2d)
arr_2d
print(type(arr_2d))
print(arr_2d.shape)
print(type(arr_2d.ndim))

<class 'numpy.ndarray'>
(2, 5)
<class 'int'>


In [11]:
lst_2d = [[1,2,3,4,5],[6,7,8,9,10]]
lst_2d
arr_2d= np.array(lst_2d)
arr_2d
print(type(arr_2d))
print(arr_2d.shape)
print(type(arr_2d.ndim))
print(arr_2d.size)
print(arr_2d.ndim)

<class 'numpy.ndarray'>
(2, 5)
<class 'int'>
10
2


In [12]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
np.arrange([1,10])

<class 'AttributeError'>: module 'numpy' has no attribute 'arrange'

In [14]:
np.arrange(1,10)

<class 'AttributeError'>: module 'numpy' has no attribute 'arrange'

In [15]:
np.arrange(10,3)

<class 'AttributeError'>: module 'numpy' has no attribute 'arrange'

In [16]:
np.range(10,3)

<class 'AttributeError'>: module 'numpy' has no attribute 'range'

In [17]:
np.arange(start=1, stop=10, step=3)

array([1, 4, 7])

In [18]:
np.arange(1, 10, 3)

array([1, 4, 7])

In [19]:
np.arange(1, 8, 3)

array([1, 4, 7])

In [20]:
np.arange(1, 10.1, 3)

array([ 1.,  4.,  7., 10.])

In [21]:
 np.arange(start=0, stop=10, step=1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(-5, -1)

array([-5, -4, -3, -2])

In [23]:
np.arange(5, 1, -1)

array([5, 4, 3, 2])

In [24]:
np.arange(5, 1, -1)

array([5, 4, 3, 2])

In [25]:
np.arange(1, 8, 3)[::-1]

array([7, 4, 1])

In [26]:
np.arange(2, 2)

array([], dtype=int32)

In [27]:
y = np.arange(5.0)
y

array([0., 1., 2., 3., 4.])

In [29]:
x = np.arange(5)
x
y = np.arange(-1, 1.1, 0.5)
y
np.abs(y)
z = np.arange(10)
z
np.sin(z)


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [30]:
a = np.arange(6).reshape((2, 3))
a
a.shape
a.ndim

2

In [31]:
import timeit
n = 1
timeit.timeit(f'x = [i**2 for i in range({n})]')
timeit.timeit(f'x = np.arange({n})**2', setup='import numpy as np')


1.251299999999901

In [32]:
list(range(10,3,-1))

[10, 9, 8, 7, 6, 5, 4]

In [33]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [34]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
np.zeros([2,3,1])

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

In [36]:
lst3= [[1,2,3],[4,5,6],[7,8,9]]
np.zero_like(lst3)

<class 'AttributeError'>: module 'numpy' has no attribute 'zero_like'

In [37]:
lst3= [[1,2,3],[4,5,6],[7,8,9]]
np.zeros_like(lst3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [38]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
lst =[[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(lst)
arr.shape

(3, 3)

In [40]:
np.random.rand(5)
np.random.randint(1,7,5)

array([5, 6, 5, 4, 2])

In [41]:
asian_countries = ["India","Bangaladesh","Bhutan","Nepal","Afghanisthan"]
asian_countries_arr = np.array(asian_countries)
asian_countries_arr.ndim
asian_countries_arr.shape
asian_countries_arr.size
asian_countries_arr.reshape(2,-1)
asian_countries_arr.reshape(3,-1)

<class 'ValueError'>: cannot reshape array of size 5 into shape (2,newaxis)

In [42]:
asian_countries = ["India","Bangaladesh","Bhutan","Nepal","Afghanisthan"]
asian_countries_arr = np.array(asian_countries)
asian_countries_arr.ndim
asian_countries_arr.shape
asian_countries_arr.size

5

In [43]:
asian_countries = ["India","Bangaladesh","Bhutan","Nepal","Afghanisthan"]
asian_countries_arr = np.array(asian_countries)
asian_countries_arr.ndim
asian_countries_arr.shape
asian_countries_arr.size
asian_countries_arr.reshape(2,-1)

<class 'ValueError'>: cannot reshape array of size 5 into shape (2,newaxis)

In [44]:
array.ravel()
array.flatten()

<class 'NameError'>: name 'array' is not defined

In [45]:
np.random(1,15)

<class 'TypeError'>: 'module' object is not callable

In [46]:

x1 = np.arange(9.0).reshape((3, 3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [47]:
x2 = np.arange(3.0)
x2

array([0., 1., 2.])

In [48]:
import numpy as np
np.subtract(1.0, 4.0)
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
np.subtract(x1, x2)

array([[0., 0., 0.],
       [3., 3., 3.],
       [6., 6., 6.]])

In [49]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
x1 - x2


array([[0., 0., 0.],
       [3., 3., 3.],
       [6., 6., 6.]])

In [50]:
import numpy as np
np.divide(2.0, 4.0)

x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
np.divide(x1, x2)

array([[nan, 1. , 1. ],
       [inf, 4. , 2.5],
       [inf, 7. , 4. ]])

In [51]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = 2 * np.ones(3)

In [52]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = 2 * np.ones(3)
x2

array([2., 2., 2.])

In [53]:
x1 = np.arange(9.0).reshape((3, 3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [54]:
x2 = 2 * np.ones(3)
x2

array([2., 2., 2.])